#!/usr/bin/env bash

set -eo pipefail

template() {

  local type=$1
  local id=$2
  local title=$3
  case "$type" in
    axiom)
      cat << EOAXIOM
# $id $title

(brief description, including a summary of benefits)

## See also

- (hyperlinked item, capitalised at start, no period at end)
EOAXIOM
      ;;
    bestpractice)
      cat << EOBESTPRACTICE
# $id $title

(brief description, using imperative form e.g. "use", "avoid", etc)

## Outcome

(summary of benefit / results)

## See also

- (hyperlinked item, capitalised at start, no period at end)
EOBESTPRACTICE
      ;;
    feature)
      cat << EOFEATURE
# $id $title

(brief description)

## Benefit

(brief description)

## See also

- (hyperlinked item, capitalised at start, no period at end)
EOFEATURE
      ;;
  esac

}

shortcode() {

  local type=$1
  local shortcode
  shortcode="${type:0:3}"
  echo "${shortcode^^}"

}

latest() {

  local type=$1
  ls -1 "${type}s/$(shortcode "$type")"*.md \
    | tail -1 \
    | grep -P -o "\d{3}"
}

next() {

  local type=$1
  local next
  next="$(latest "$type")"
  ((next++))
  printf "%03d" "$next"

}

new() {

  local type=$1
  local next
  local file
  local id
  next="$(next "$type")"
  id="$(shortcode "$type")${next}"
  file="${type}s/${id}.md"
  template "$type" "$id" "$title" > "$file"
  "$EDITOR" "$file"

}

main() {

  local type title
  type="${0##*/}"
  title="${1:?"Specify title for ${type}"}"
  grep -q -E "^(axiom|bestpractice|feature)$" <<< "$type"
  new "$type" "$title"

}

main "$@"
